// Package toolpackage provides Dockerfile generation for tool images.
package toolpackage

import (
	"fmt"
	"strings"
	"text/template"
)

// dockerfileTemplate is the base template for generating Dockerfiles.
//
// Tool images contain ONLY the CLI binary, base utilities, and optional deny
// patterns. The capability-gateway binary is NOT included — the agent-operator
// injects it at runtime via an init container that copies the binary from the
// gateway image into a shared emptyDir volume. All sidecar containers then use
// the injected binary as their entrypoint (the operator overrides the image's
// command). This decouples tool image versions from gateway versions and allows
// centralized gateway updates without rebuilding tool images.
const dockerfileTemplate = `# Generated by agent-tools build
# Tool: {{.Metadata.Name}} v{{.Metadata.Version}}
# Install method: {{.InstallMethod}}
#
# NOTE: This image contains only the CLI tool. The capability-gateway binary
# is injected at runtime by the agent-operator via init container.

{{if eq .InstallMethod "go"}}
# Stage 1: Build Go CLI tool — runs natively, cross-compiles for TARGETARCH
FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS cli-builder
ARG TARGETARCH
RUN GOARCH=$TARGETARCH go install {{.CLI.Go}}
{{end}}

# Final image
{{if eq .InstallMethod "pip"}}
FROM python:3.12-alpine
{{else if eq .InstallMethod "npm"}}
FROM node:22-alpine
{{else}}
FROM alpine:3.21
{{end}}

# TARGETARCH is provided automatically by Docker buildx (amd64, arm64, etc.)
ARG TARGETARCH

# Install base utilities
RUN apk add --no-cache ca-certificates curl jq wget

{{if eq .InstallMethod "apk"}}
# Install CLI via Alpine package
RUN apk add --no-cache {{.CLI.APK}}
{{else if eq .InstallMethod "download"}}
# Download CLI binary
{{if .CLI.Download.Extract}}
{{if eq .CLI.Download.Extract "tar.gz"}}
RUN wget -qO- "{{.CLI.Download.URL}}" | tar xzf - -C /tmp && \
    mv "/tmp/{{.CLI.Download.Path}}" /usr/local/bin/{{.CLI.Binary}} && \
    chmod {{or .CLI.Download.Chmod "755"}} /usr/local/bin/{{.CLI.Binary}} && \
    rm -rf /tmp/*
{{else if eq .CLI.Download.Extract "tar.xz"}}
RUN apk add --no-cache xz && \
    wget -qO- "{{.CLI.Download.URL}}" | tar xJf - -C /tmp && \
    mv "/tmp/{{.CLI.Download.Path}}" /usr/local/bin/{{.CLI.Binary}} && \
    chmod {{or .CLI.Download.Chmod "755"}} /usr/local/bin/{{.CLI.Binary}} && \
    rm -rf /tmp/* && \
    apk del xz
{{else if eq .CLI.Download.Extract "zip"}}
RUN wget -qO /tmp/cli.zip "{{.CLI.Download.URL}}" && \
    unzip -q /tmp/cli.zip -d /tmp && \
    mv "/tmp/{{.CLI.Download.Path}}" /usr/local/bin/{{.CLI.Binary}} && \
    chmod {{or .CLI.Download.Chmod "755"}} /usr/local/bin/{{.CLI.Binary}} && \
    rm -rf /tmp/*
{{end}}
{{else}}
RUN wget -qO /usr/local/bin/{{.CLI.Binary}} "{{.CLI.Download.URL}}" && \
    chmod {{or .CLI.Download.Chmod "755"}} /usr/local/bin/{{.CLI.Binary}}
{{end}}
{{else if eq .InstallMethod "pip"}}
# Install CLI via pip
RUN pip install --no-cache-dir {{.CLI.Pip}}
{{else if eq .InstallMethod "npm"}}
# Install CLI via npm
RUN npm install -g {{.CLI.NPM}}
{{else if eq .InstallMethod "go"}}
# Copy CLI from Go builder stage
COPY --from=cli-builder /go/bin/{{.CLI.Binary}} /usr/local/bin/{{.CLI.Binary}}
{{end}}

# Create config directory
RUN mkdir -p /etc/tool

{{if .Deny}}
# Embedded deny patterns (immutable security baseline)
COPY deny.txt /etc/tool/deny.txt
{{end}}

# Create non-root user
RUN adduser -D -u 1000 tool
USER tool
`

// GenerateDockerfile generates a Dockerfile for the given ToolPackage.
func GenerateDockerfile(pkg *ToolPackage) (string, error) {
	if err := pkg.Validate(); err != nil {
		return "", fmt.Errorf("invalid package: %w", err)
	}

	// Create template with helper functions
	tmpl, err := template.New("dockerfile").Funcs(template.FuncMap{
		"or": func(a, b string) string {
			if a != "" {
				return a
			}
			return b
		},
	}).Parse(dockerfileTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, pkg); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// GenerateDenyFile generates the deny.txt file content from deny patterns.
func GenerateDenyFile(patterns []string) string {
	if len(patterns) == 0 {
		return ""
	}

	var buf strings.Builder
	buf.WriteString("# Embedded deny patterns - these cannot be overridden by the Tool CRD\n")
	buf.WriteString("# Generated by agent-tools build\n\n")

	for _, pattern := range patterns {
		buf.WriteString(pattern)
		buf.WriteString("\n")
	}

	return buf.String()
}
